### ISSUE TITLE
Don't work with Expanded Storage?

### ISSUE THREAD

**Issue by talkerswe** [AbsolemJackdaw/EasierChests-Forge#2]
Hello there!
I can't get it to work with the Expanded Storage mod.
It works perfect with regular vanilla chests but not the modded ones. I have enabled large chests in the config aswell.

In the log i found:
"EasierChests did not find mod Expanded Storage, not enabling support"

I tried to troubleshoot it myself but i dont know much about code, tho my suspicion is the recent renaming of the depency mod Expanded Storage require. 
Ninjaphenix's Container Library have changed name to Ellemes' Container Library.

And i saw that your mod makes som api call(i think?) to something called like "ninjaphenix.container_library.api". 
And i believe i saw that there was some api renaming on the Elleme's Container Library github page. 

That is my amateur analysis
But as i said, i can't write or understand most of code and can be very wrong :)

Client Verisions:
- Minecraft 1.18.2
- Forge 40.1.31

Mods Verisions:
- easierchests-1.0.2.jar
- ellemes-container-library-1.4.0-beta.2+1.18.2-forge.jar
- expandedstorage-7.4.0-beta.3+1.18.2-forge.jar

I am currently not home so i can't provide my log, but tell me if you need it and i will post it as soon as i get home.

Thanks in Advance
/R

**Comment by AbsolemJackdaw** [comment]
I have just looked at the API and it seems like it's the same in 1.18.2 as it was before. the path hasn't changed. I will however take a deeper look to see why the mod fails to find it

**Comment by talkerswe** [comment]
Then my troubleshooting showed just how little i know about code, as i said haha! :)

I was thinking if it can have something to do with the order they are loaded in for som reason? 
Because i noticed that the "not enabling support" line was pretty early in the log in comparision for expanded storage, it was mentioned for the first time waaay down in the log.

The log if it helps:
https://paste.ee/p/QavsJ


And btw, i REALLY REALLY appreciate that you are taking a look at it and responded so fast, and if i can help somehow just let me know. 
This is easily my favorite mod of them all and when i saw that someone ported it to forge i was super happy to be able to use it even on my create server!

**Comment by AbsolemJackdaw** [comment]
> And btw, i REALLY REALLY appreciate that you are taking a look at it and responded so fast, and if i can help somehow just let me know.
easier to procrastinate on my finals ...

i'm trying to make modding a wel paying hobby, end-user satisfaction is a high priority for me.
I found out then while porting, the compat got commented out and dint make it back in. 
currently talking with Ellemes to make it work again, given they did indeed change their API around a bunch

**Comment by talkerswe** [comment]
Oh! Does that mean that you have located the problem? :)
Looking forward to the solution! (No rush tho! Take your time!)

Love the mindset and priority from you!
When i browse through looking for new mods or updates i have noticed to many people who create mods that have little to no documentation/descriptions/wiki/screenshots for their creation, long response times/if any at all. 
And some even have a really bad attitude when they bother to answer people. I get that it´s annoying to see 300 different "1.11.4 Please" e.g in the comments and so on, but come on :P

**Comment by talkerswe** [comment]
To show my appreciation and as a thanks, i did the only thing i can help with, and that is my language!

![bild](https://user-images.githubusercontent.com/62042533/172255574-a177bd46-4193-4e98-9ec6-dc771c3b7f9e.png)

**Comment by AbsolemJackdaw** [comment]
nice. is that giselbaer's translation website ? 

i'll be releasing a beta for testing purposes. I don't have time right now to test it toroughly . changes have been made, it should work now with the beta latest release of the container lib. the other mods havent been added yet, but expanded storage should work. 
i hope to hear from you again soon ! just gotta wait five minutes for the file to be accepted on curseforge and go trough mdoeration.

**Comment by talkerswe** [comment]
Oh, yeah i guess its his, i just clicked the link in the top of the description, didn´t think about that it´s a copy from the other one :) I am not really 100% on how stuff on github works with forks/pull request etc, it´s a jungle for a novice :)

Oh really? That was fast! :D
Thank you!! I will try it out right away!
I really only care about Expanded Storage for now so the beta is all i need hehe.

**Comment by talkerswe** [comment]
Tried it out now and it works like a charm! My life is now complete! Haha.

Just to mention, the arrows for the row underneath the inventory ends upp somewhere in middle of the inventory, easy just to disable in config so i will do that, but then you know atlest :)

Once again, THANK YOU!
