### ISSUE TITLE
Add support for Sophisticated Backpacks?

### ISSUE THREAD

**Issue by talkerswe** [AbsolemJackdaw/EasierChests-Forge#3]
Hello good sir!

I was wondering about the possibility to add support for Sophisticated Backpacks mod?

Would be great :)

Link to mod:
https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/176944717-cce8f05e-4042-49f8-be94-8de6fa17269e.png)

on its way

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/177047468-f655adbf-6e91-45dc-bdcd-60486378d278.png)
slowly advancing

**Comment by AbsolemJackdaw** [comment]
It's in beta.
1.18 https://www.curseforge.com/minecraft/mc-mods/easierchests-2/files/3859433
1.19 https://www.curseforge.com/minecraft/mc-mods/easierchests-2/files/3859446
if you find anything weird apart from the buttons not scrolling, please do tell

**Comment by talkerswe** [comment]
Oh my god you are amazing! Thank you! I will try it out really soon :D
